# Render.com Blueprint for SafeAPI-Bridge
# This file automates deployment of the proxy server with PostgreSQL and optional Redis

services:
  # Web Service - Node.js Server
  - type: web
    name: safeapi-bridge
    env: node
    region: oregon # or any other region
    plan: starter # Free tier
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /health

    # Auto-deploy on push to main
    branch: main

    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000 # Render default

      - key: JWT_SECRET
        generateValue: true # Auto-generate secure secret

      - key: ADMIN_API_KEY
        generateValue: true # Auto-generate admin key

      - key: DATABASE_URL
        fromDatabase:
          name: safeapi-db
          property: connectionString

      # Use Redis internal URL from Redis service below (if present)
      - key: REDIS_URL
        fromService:
          name: safeapi-redis
          type: redis
          property: connectionString

      # API Keys (add these manually in Render dashboard or via sync)
      - key: OPENAI_API_KEY
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: CLAUDE_API_KEY
        sync: false

      - key: GROQ_API_KEY
        sync: false

      - key: MISTRAL_API_KEY
        sync: false

      # Optional Redis URL (if you add Redis service)
      - key: REDIS_URL
        sync: false

      # CORS
      - key: ALLOWED_ORIGINS
        value: "*" # Change to your domain in production

      # Rate Limiting
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

      - key: RATE_LIMIT_WINDOW_MS
        value: 3600000

# Database - PostgreSQL
databases:
  - name: safeapi-db
    databaseName: safeapi_bridge
    user: safeapi_user
    plan: starter # Free tier (90 days)
    region: oregon
    postgresMajorVersion: 15

# Optional: Redis (uncomment if you want Redis caching)
redis:
  - name: safeapi-redis
    plan: starter # Free tier (30 days)
    region: oregon
    maxmemoryPolicy: allkeys-lru
